### ISSUE TITLE
大佬能出个文档讲下架构吗？

### ISSUE THREAD

**Issue by ebaecff** [makeryangcom/Engine2D#7]
大佬能出个文档讲下架构吗？

**Comment by ebaecff** [comment]
B站过来的，不懂网络游戏的 server - client 架构，主要是数据同步（状态同步、帖同步）怎么做的

**Comment by makeryangcom** [comment]
> B站过来的，不懂网络游戏的 server - client 架构，主要是数据同步（状态同步、帖同步）怎么做的

你可以看下源码。

**Comment by ebaecff** [comment]
> > B站过来的，不懂网络游戏的 server - client 架构，主要是数据同步（状态同步、帖同步）怎么做的
> 
> 你可以看下源码。

水平不够啊

**Comment by makeryangcom** [comment]
我目前也没有太多时间弄资料，还在开发、摸索阶段。

**Comment by ebaecff** [comment]
嗯嗯，大佬的教学视频还录吗？
